/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.Dolph.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.Dolph.domain.User;
import com.Dolph.service.UserService;
import com.Dolph.web.struts.form.RegisterUserForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-04-2013
 * 
 * XDoclet definition:
 * @struts.action path="/registerUser" name="registerUserForm" scope="request" validate="true"
 */
public class RegisterUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterUserForm registerUserForm = (RegisterUserForm) form;
		User user=new User();
		user.setUsername(registerUserForm.getUsername());
		user.setPassword(registerUserForm.getPassword());
		
		UserService userservice=new UserService();
		if(userservice.checkUsername(user.getUsername())){
			System.out.println("1");
			userservice.register(user);
		}
		else{
			request.setAttribute("errinfo","用户名已存在");
			return mapping.findForward("err");
		}
		
		return mapping.findForward("gologin");
	}
}