/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.Dolph.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.Dolph.web.struts.form.LoginUserForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-04-2013
 * 
 * XDoclet definition:
 * @struts.action path="/user" name="loginUserForm" scope="request" validate="true"
 */
public class UserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginUserForm loginUserForm = (LoginUserForm) form;// TODO Auto-generated method stub
		return null;
	}
}